name: Bug Report
description: Report a bug or unexpected behavior in FOVEA
title: "[Bug]: "
labels: ["bug", "needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for reporting a bug! Please fill out the sections below to help us understand and fix the issue.

  - type: textarea
    id: description
    attributes:
      label: Description
      description: A clear and concise description of what the bug is.
      placeholder: When I do X, Y happens instead of Z...
    validations:
      required: true

  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to Reproduce
      description: Detailed steps to reproduce the behavior.
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. Scroll down to '...'
        4. See error
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected Behavior
      description: What you expected to happen.
      placeholder: I expected the annotation to save successfully...
    validations:
      required: true

  - type: textarea
    id: actual-behavior
    attributes:
      label: Actual Behavior
      description: What actually happened.
      placeholder: The annotation was not saved and an error appeared...
    validations:
      required: true

  - type: dropdown
    id: component
    attributes:
      label: Affected Component
      description: Which part of FOVEA is affected?
      options:
        - Frontend (Annotation Tool)
        - Backend (API Server)
        - Model Service
        - Documentation
        - Docker/Infrastructure
        - Not sure
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: FOVEA Version
      description: What version of FOVEA are you running? (Check package.json or docker image tag)
      placeholder: "v1.0.0 or commit hash"
    validations:
      required: false

  - type: dropdown
    id: deployment
    attributes:
      label: Deployment Method
      description: How are you running FOVEA?
      options:
        - Docker Compose (CPU mode)
        - Docker Compose (GPU mode)
        - Manual installation
        - Other
    validations:
      required: false

  - type: input
    id: browser
    attributes:
      label: Browser
      description: If this is a frontend issue, which browser are you using?
      placeholder: "Chrome 120, Firefox 121, Safari 17, etc."
    validations:
      required: false

  - type: input
    id: os
    attributes:
      label: Operating System
      description: What OS are you running?
      placeholder: "macOS 14, Ubuntu 22.04, Windows 11, etc."
    validations:
      required: false

  - type: textarea
    id: logs
    attributes:
      label: Relevant Logs
      description: Please paste any relevant log output. This will be automatically formatted as code.
      render: shell
    validations:
      required: false

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots or Videos
      description: If applicable, add screenshots or videos to help explain the problem. You can drag and drop files here.
    validations:
      required: false

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context about the problem here (GPU model, video format, dataset size, etc.).
    validations:
      required: false

  - type: checkboxes
    id: checklist
    attributes:
      label: Before Submitting
      description: Please confirm the following
      options:
        - label: I have searched existing issues to avoid duplicates
          required: true
        - label: I have provided all relevant information above
          required: true
