name: Feature Request
description: Suggest a new feature or enhancement for FOVEA
title: "[Feature]: "
labels: ["enhancement", "needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for suggesting a feature! Please describe the problem you're trying to solve and your proposed solution.

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem does this feature solve? What use case does it address?
      placeholder: As a [type of user], I want to [do something] so that [benefit/value]...
    validations:
      required: true

  - type: textarea
    id: proposed-solution
    attributes:
      label: Proposed Solution
      description: How would you like this feature to work?
      placeholder: Describe the feature in detail, including UI/UX considerations if applicable...
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Have you considered any alternative solutions or workarounds?
      placeholder: I tried X but it doesn't work because Y...
    validations:
      required: false

  - type: dropdown
    id: component
    attributes:
      label: Affected Component
      description: Which part of FOVEA would this feature affect?
      options:
        - Frontend (Annotation Tool)
        - Backend (API Server)
        - Model Service
        - Documentation
        - Docker/Infrastructure
        - Multiple components
        - Not sure
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature to you?
      options:
        - Critical (blocking my work)
        - High (would significantly improve my workflow)
        - Medium (nice to have)
        - Low (minor improvement)
    validations:
      required: true

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context, screenshots, mockups, or examples about the feature request here.
    validations:
      required: false

  - type: checkboxes
    id: contribution
    attributes:
      label: Contribution
      description: Would you be willing to contribute this feature?
      options:
        - label: I am willing to submit a pull request for this feature
          required: false

  - type: checkboxes
    id: checklist
    attributes:
      label: Before Submitting
      description: Please confirm the following
      options:
        - label: I have searched existing issues and feature requests to avoid duplicates
          required: true
        - label: This feature aligns with FOVEA's goals as a video annotation tool
          required: true
