// The pub.layers.* annotation vocabulary — the single source of annotation
// types shared by the Fovea server and frontend.
//
// The contents of ./generated are produced from the layers lexicons by
// layers-codegen (see scripts/regenerate.sh) and are vendored verbatim. Do not
// edit ./generated by hand; edit the lexicons and regenerate. UI-only or
// Fovea-only extension types belong in sibling modules, never in ./generated.
//
// This barrel bypasses the generated top-level `index.ts` on purpose: that
// barrel re-exports an empty `examples` module and blanket-star-exports both
// `changelog` and `resource`, which each declare an `Entry` record (the only
// cross-namespace name collision). We alias both — matching the generated
// `family.ts`'s `ChangelogEntry`/`ResourceEntry` naming — and skip `examples`.

// Shared definitions: Span, Anchor, BoundingBox, TemporalSpan,
// SpatioTemporalAnchor, Keyframe, TokenRef(Sequence), ObjectRef, FeatureMap, ...
export * from './generated/pub/layers/defs'

// Record namespaces (collision-free).
export * from './generated/pub/layers/alignment/index'
export * from './generated/pub/layers/annotation/index'
export * from './generated/pub/layers/corpus/index'
export * from './generated/pub/layers/eprint/index'
export * from './generated/pub/layers/expression/index'
export * from './generated/pub/layers/graph/index'
export * from './generated/pub/layers/judgment/index'
export * from './generated/pub/layers/media/index'
export * from './generated/pub/layers/ontology/index'
export * from './generated/pub/layers/persona/index'
export * from './generated/pub/layers/segmentation/index'

// changelog and resource both export `Entry`; alias both so the bare name is
// unambiguous.
export * from './generated/pub/layers/changelog/defs'
export type { Entry as ChangelogEntry } from './generated/pub/layers/changelog/entry'
export * from './generated/pub/layers/resource/collection'
export * from './generated/pub/layers/resource/collection_membership'
export * from './generated/pub/layers/resource/defs'
export * from './generated/pub/layers/resource/filling'
export * from './generated/pub/layers/resource/template'
export * from './generated/pub/layers/resource/template_composition'
export type { Entry as ResourceEntry } from './generated/pub/layers/resource/entry'

// Record-family dispatch: AnyRecord, NSID map, RecordTypes, isX guards,
// tagRecord, decodeRecord, toTypedJson.
export * from './generated/family'
