/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/detection/detect": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Detect objects in video frames. */
        post: operations["post_/api/detection/detect"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/extract-claims": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Extract claims from a generated summary. */
        post: operations["post_/api/extract-claims"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ontology/augment": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Suggest ontology types for a persona domain. */
        post: operations["post_/api/ontology/augment"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/summarize": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Summarize a video for a persona. */
        post: operations["post_/api/summarize"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/synthesize-summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Synthesize a summary gloss from claim sources. */
        post: operations["post_/api/synthesize-summary"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AudioOverrides
         * @description Per-request overrides for transcription and diarization.
         */
        AudioOverrides: {
            /**
             * Beam Size
             * @description Decoder beam width
             * @default null
             */
            beam_size?: number | null;
            /**
             * Compute Type
             * @description Transcriber compute precision
             * @default null
             */
            compute_type?: ("float16" | "float32" | "int8" | "int8_float16") | null;
            /**
             * Max Speakers
             * @default null
             */
            max_speakers?: number | null;
            /**
             * Min Speakers
             * @default null
             */
            min_speakers?: number | null;
            /**
             * Num Speakers
             * @description Exact speaker count (skips auto-detect)
             * @default null
             */
            num_speakers?: number | null;
            /**
             * Vad Threshold
             * @description Voice-activity detection probability threshold
             * @default null
             */
            vad_threshold?: number | null;
        };
        /**
         * AugmentRequest
         * @description Request body for the ontology augmentation endpoint.
         */
        AugmentRequest: {
            /**
             * Domain
             * @description Domain description for context
             */
            domain: string;
            /**
             * Existing Types
             * @description Existing type names
             */
            existing_types?: string[];
            /**
             * Max Suggestions
             * @description Maximum suggestions to return
             * @default 10
             */
            max_suggestions?: number;
            /**
             * Persona Id
             * @description Unique identifier for the persona
             */
            persona_id: string;
            /**
             * Target Category
             * @description Category to augment
             * @enum {string}
             */
            target_category: "entity" | "event" | "role" | "relation";
        };
        /**
         * AugmentResponse
         * @description Response body for the ontology augmentation endpoint.
         */
        AugmentResponse: {
            /**
             * Id
             * @description Unique identifier for this augmentation
             */
            id: string;
            /**
             * Persona Id
             * @description Persona identifier
             */
            persona_id: string;
            /**
             * Reasoning
             * @description Explanation of why these types were suggested
             */
            reasoning: string;
            /**
             * Suggestions
             * @description Suggested types
             */
            suggestions?: components["schemas"]["OntologyType"][];
            /**
             * Target Category
             * @description Category that was augmented
             */
            target_category: string;
        };
        /**
         * BoundingBox
         * @description Bounding box coordinates, normalized to [0, 1].
         */
        BoundingBox: {
            /**
             * Height
             * @description Box height (normalized)
             */
            height: number;
            /**
             * Width
             * @description Box width (normalized)
             */
            width: number;
            /**
             * X
             * @description X coordinate (normalized)
             */
            x: number;
            /**
             * Y
             * @description Y coordinate (normalized)
             */
            y: number;
        };
        /**
         * ClaimExtractionRequest
         * @description Request body for the claim extraction endpoint.
         */
        ClaimExtractionRequest: {
            /**
             * Annotations
             * @description Annotation data for context
             * @default null
             */
            annotations?: {
                [key: string]: components["schemas"]["JsonValue"];
            }[] | null;
            /**
             * Extraction Strategy
             * @description Strategy for extracting claims
             * @default sentence-based
             * @enum {string}
             */
            extraction_strategy?: "sentence-based" | "semantic-units" | "hierarchical";
            /**
             * Max Claims
             * @description Maximum number of claims to extract
             * @default 50
             */
            max_claims?: number;
            /**
             * Min Confidence
             * @description Minimum confidence threshold for claims
             * @default 0.5
             */
            min_confidence?: number;
            /**
             * Ontology Glosses
             * @description Map of type ID to gloss text
             * @default null
             */
            ontology_glosses?: {
                [key: string]: string;
            } | null;
            /**
             * Ontology Types
             * @description Ontology type definitions for context
             * @default null
             */
            ontology_types?: {
                [key: string]: components["schemas"]["JsonValue"];
            }[] | null;
            /**
             * Sentences
             * @description Pre-split sentences (optional)
             * @default null
             */
            sentences?: string[] | null;
            /**
             * Summary Id
             * @description Unique identifier for the summary
             */
            summary_id: string;
            /**
             * Summary Text
             * @description Full summary text to extract claims from
             */
            summary_text: string;
        };
        /**
         * ClaimExtractionResponse
         * @description Response body for the claim extraction endpoint.
         */
        ClaimExtractionResponse: {
            /**
             * Claims
             * @description Extracted claims
             */
            claims?: components["schemas"]["ExtractedClaim"][];
            /**
             * Model Used
             * @description LLM model used for extraction
             */
            model_used: string;
            /**
             * Processing Time
             * @description Processing time in seconds
             */
            processing_time: number;
            /**
             * Summary Id
             * @description Summary identifier
             */
            summary_id: string;
        };
        /**
         * ClaimRelationship
         * @description Relationship between claims across sources.
         */
        ClaimRelationship: {
            /**
             * Confidence
             * @description Confidence score
             * @default 0.8
             */
            confidence?: number;
            /**
             * Notes
             * @description Optional notes
             * @default null
             */
            notes?: string | null;
            /**
             * Relation Type
             * @description Type of relationship
             * @enum {string}
             */
            relation_type: "supports" | "conflicts_with" | "contradicts" | "refines" | "generalizes" | "duplicates";
            /**
             * Source Claim Id
             * @description Source claim ID
             */
            source_claim_id: string;
            /**
             * Target Claim Id
             * @description Target claim ID
             */
            target_claim_id: string;
        };
        /**
         * ClaimSource
         * @description Source of claims for synthesis (single video or collection).
         */
        ClaimSource: {
            /**
             * Claims
             * @description Hierarchical claim structure
             */
            claims?: {
                [key: string]: components["schemas"]["JsonValue"];
            }[];
            /**
             * Metadata
             * @description Source metadata (video title, date, etc.)
             * @default null
             */
            metadata?: {
                [key: string]: components["schemas"]["JsonValue"];
            } | null;
            /**
             * Source Id
             * @description Video ID or collection ID
             */
            source_id: string;
            /**
             * Source Type
             * @description Type of source
             * @enum {string}
             */
            source_type: "video" | "collection";
        };
        /**
         * Detection
         * @description Single object detection result.
         */
        Detection: {
            /** @description Bounding box coordinates */
            bounding_box: components["schemas"]["BoundingBox"];
            /**
             * Confidence
             * @description Detection confidence score
             */
            confidence: number;
            /**
             * Label
             * @description Detected object label
             */
            label: string;
            /**
             * Track Id
             * @description Tracking ID across frames
             * @default null
             */
            track_id?: string | null;
        };
        /**
         * DetectionRequest
         * @description Request body for the object detection endpoint.
         */
        DetectionRequest: {
            /**
             * Confidence Threshold
             * @description Minimum confidence for detections
             * @default 0.3
             */
            confidence_threshold?: number;
            /**
             * Enable Tracking
             * @description Whether to enable object tracking
             * @default true
             */
            enable_tracking?: boolean;
            /**
             * Frame Numbers
             * @description Specific frames to process
             */
            frame_numbers?: number[];
            /**
             * Query
             * @description Text query describing objects to detect
             */
            query: string;
            /**
             * Video Id
             * @description Unique identifier for the video
             */
            video_id: string;
            /**
             * Video Path
             * @description Optional full path to video file
             * @default null
             */
            video_path?: string | null;
        };
        /**
         * DetectionResponse
         * @description Response body for the object detection endpoint.
         */
        DetectionResponse: {
            /**
             * Frames
             * @description Frames with detections
             */
            frames?: components["schemas"]["FrameDetections"][];
            /**
             * Id
             * @description Unique identifier for this detection job
             */
            id: string;
            /**
             * Processing Time
             * @description Processing time in seconds
             */
            processing_time: number;
            /**
             * Query
             * @description Query that was used
             */
            query: string;
            /**
             * Total Detections
             * @description Total detections across all frames
             */
            total_detections: number;
            /**
             * Video Id
             * @description Video identifier
             */
            video_id: string;
        };
        /**
         * ExtractedClaim
         * @description Single extracted claim with metadata and nested subclaims.
         */
        ExtractedClaim: {
            /**
             * Char End
             * @description Character offset end in summary text
             * @default null
             */
            char_end?: number | null;
            /**
             * Char Start
             * @description Character offset in summary text
             * @default null
             */
            char_start?: number | null;
            /**
             * Claim Type
             * @description Semantic type of claim
             * @default null
             */
            claim_type?: string | null;
            /**
             * Confidence
             * @description Model confidence in claim extraction
             */
            confidence: number;
            /**
             * Sentence Index
             * @description Index of source sentence (if sentence-based)
             * @default null
             */
            sentence_index?: number | null;
            /**
             * Subclaims
             * @description Nested subclaims
             */
            subclaims?: components["schemas"]["ExtractedClaim"][];
            /**
             * Text
             * @description Claim text
             */
            text: string;
            /**
             * @description Optional reasoning trace from a thinking-capable model
             * @default null
             */
            thinking?: components["schemas"]["ThinkingTrace"] | null;
        };
        /**
         * FrameDetections
         * @description Detections for a single video frame.
         */
        FrameDetections: {
            /**
             * Detections
             * @description Detections in this frame
             */
            detections?: components["schemas"]["Detection"][];
            /**
             * Frame Number
             * @description Frame number in the video
             */
            frame_number: number;
            /**
             * Timestamp
             * @description Time in seconds from video start
             */
            timestamp: number;
        };
        /**
         * GenerationOverrides
         * @description Per-request overrides for LLM/VLM sampling parameters.
         */
        GenerationOverrides: {
            /**
             * Max Tokens
             * @description Maximum tokens to generate
             * @default null
             */
            max_tokens?: number | null;
            /**
             * Temperature
             * @description Sampling temperature override
             * @default null
             */
            temperature?: number | null;
            /**
             * Top P
             * @description Nucleus sampling probability mass
             * @default null
             */
            top_p?: number | null;
        };
        /** @description An arbitrary JSON value. */
        JsonValue: string | number | boolean | unknown[] | {
            [key: string]: unknown;
        } | null;
        /**
         * KeyFrame
         * @description Key frame information from video analysis.
         */
        KeyFrame: {
            /**
             * Confidence
             * @description Model confidence score
             * @default 0
             */
            confidence?: number;
            /**
             * Description
             * @description Frame description
             */
            description: string;
            /**
             * Frame Number
             * @description Frame number in the video
             */
            frame_number: number;
            /**
             * Timestamp
             * @description Time in seconds from video start
             */
            timestamp: number;
        };
        /**
         * OntologyType
         * @description Suggested ontology type from augmentation.
         */
        OntologyType: {
            /**
             * Confidence
             * @description Confidence score
             * @default 0
             */
            confidence?: number;
            /**
             * Description
             * @description Type description
             */
            description: string;
            /**
             * Examples
             * @description Example instances
             */
            examples?: string[];
            /**
             * Name
             * @description Type name
             */
            name: string;
            /**
             * Parent
             * @description Parent type name
             * @default null
             */
            parent?: string | null;
            /**
             * @description Optional reasoning trace from a thinking-capable model
             * @default null
             */
            thinking?: components["schemas"]["ThinkingTrace"] | null;
        };
        /**
         * SummarizeRequest
         * @description Request body for the video summarization endpoint.
         */
        SummarizeRequest: {
            /**
             * Audio Language
             * @description Audio language code (e.g., 'en')
             * @default null
             */
            audio_language?: string | null;
            /**
             * @description Per-request transcription/diarization overrides
             * @default null
             */
            audio_overrides?: components["schemas"]["AudioOverrides"] | null;
            /**
             * Enable Audio
             * @description Enable audio transcription
             * @default false
             */
            enable_audio?: boolean;
            /**
             * Enable Speaker Diarization
             * @description Enable speaker identification
             * @default false
             */
            enable_speaker_diarization?: boolean;
            /**
             * Frame Sample Rate
             * @description Frames to sample per second
             * @default 1
             */
            frame_sample_rate?: number;
            /**
             * Fusion Strategy
             * @description Audio-visual fusion strategy
             * @default sequential
             */
            fusion_strategy?: ("sequential" | "timestamp_aligned" | "native_multimodal" | "hybrid") | null;
            /**
             * @description Per-request VLM sampling overrides
             * @default null
             */
            generation_overrides?: components["schemas"]["GenerationOverrides"] | null;
            /**
             * Information Need
             * @description Optional information need for context
             * @default null
             */
            information_need?: string | null;
            /**
             * Max Frames
             * @description Maximum frames to process
             * @default 30
             */
            max_frames?: number;
            /**
             * Persona Id
             * @description Unique identifier for the persona
             */
            persona_id: string;
            /**
             * Persona Role
             * @description Optional persona role for context
             * @default null
             */
            persona_role?: string | null;
            /**
             * Video Id
             * @description Unique identifier for the video
             */
            video_id: string;
            /**
             * Video Path
             * @description Optional full path to video file
             * @default null
             */
            video_path?: string | null;
        };
        /**
         * SummarizeResponse
         * @description Response body for the video summarization endpoint.
         */
        SummarizeResponse: {
            /**
             * Audio Language
             * @description Detected audio language code
             * @default null
             */
            audio_language?: string | null;
            /**
             * Audio Model Used
             * @description Audio transcription model name
             * @default null
             */
            audio_model_used?: string | null;
            /**
             * Audio Transcript
             * @description Transcribed audio content
             * @default null
             */
            audio_transcript?: string | null;
            /**
             * Confidence
             * @description Overall confidence score
             * @default 0
             */
            confidence?: number;
            /**
             * Fusion Strategy
             * @description Fusion strategy used
             * @default null
             */
            fusion_strategy?: string | null;
            /**
             * Id
             * @description Unique identifier for this summary
             */
            id: string;
            /**
             * Key Frames
             * @description Key frames with descriptions
             */
            key_frames?: components["schemas"]["KeyFrame"][];
            /**
             * Persona Id
             * @description Persona identifier
             */
            persona_id: string;
            /**
             * Processing Time Audio
             * @description Audio processing time in seconds
             * @default null
             */
            processing_time_audio?: number | null;
            /**
             * Processing Time Fusion
             * @description Fusion processing time in seconds
             * @default null
             */
            processing_time_fusion?: number | null;
            /**
             * Processing Time Visual
             * @description Visual processing time in seconds
             * @default null
             */
            processing_time_visual?: number | null;
            /**
             * Speaker Count
             * @description Number of distinct speakers
             * @default null
             */
            speaker_count?: number | null;
            /**
             * Summary
             * @description Text summary of video content
             */
            summary: string;
            /**
             * @description Optional reasoning trace from a thinking-capable model
             * @default null
             */
            thinking?: components["schemas"]["ThinkingTrace"] | null;
            /**
             * Transcript Json
             * @description Structured transcript with segments
             * @default null
             */
            transcript_json?: {
                [key: string]: components["schemas"]["JsonValue"];
            } | null;
            /**
             * Video Id
             * @description Video identifier
             */
            video_id: string;
            /**
             * Visual Analysis
             * @description Detailed visual content analysis
             * @default null
             */
            visual_analysis?: string | null;
            /**
             * Visual Model Used
             * @description Visual analysis model name
             * @default null
             */
            visual_model_used?: string | null;
        };
        /**
         * SummarySynthesisRequest
         * @description Request body for the summary synthesis endpoint.
         */
        SummarySynthesisRequest: {
            /**
             * Claim Relations
             * @description Relationships between claims
             * @default null
             */
            claim_relations?: components["schemas"]["ClaimRelationship"][] | null;
            /**
             * Claim Sources
             * @description Claim hierarchies from one or more sources
             */
            claim_sources: components["schemas"]["ClaimSource"][];
            /**
             * Include Citations
             * @description Include inline citations to source claims
             * @default false
             */
            include_citations?: boolean;
            /**
             * Include Conflicts
             * @description Explicitly mention informational conflicts
             * @default true
             */
            include_conflicts?: boolean;
            /**
             * Max Length
             * @description Maximum summary length in words
             * @default 500
             */
            max_length?: number;
            /**
             * Ontology Context
             * @description Ontology types and glosses for references
             * @default null
             */
            ontology_context?: {
                [key: string]: components["schemas"]["JsonValue"];
            } | null;
            /**
             * Persona Context
             * @description Persona information for perspective
             * @default null
             */
            persona_context?: {
                [key: string]: components["schemas"]["JsonValue"];
            } | null;
            /**
             * Summary Id
             * @description Target summary identifier
             */
            summary_id: string;
            /**
             * Synthesis Strategy
             * @description Strategy for organizing summary
             * @default hierarchical
             * @enum {string}
             */
            synthesis_strategy?: "hierarchical" | "chronological" | "narrative" | "analytical";
        };
        /**
         * SummarySynthesisResponse
         * @description Response body for the summary synthesis endpoint.
         */
        SummarySynthesisResponse: {
            /**
             * Claims Used
             * @description Total claims synthesized
             */
            claims_used: number;
            /**
             * Model Used
             * @description LLM model used for synthesis
             */
            model_used: string;
            /**
             * Processing Time
             * @description Processing time in seconds
             */
            processing_time: number;
            /**
             * Summary Gloss
             * @description Generated summary as GlossItem array with references
             */
            summary_gloss?: {
                [key: string]: components["schemas"]["JsonValue"];
            }[];
            /**
             * Summary Id
             * @description Summary identifier
             */
            summary_id: string;
            /**
             * Synthesis Metadata
             * @description Metadata about synthesis
             */
            synthesis_metadata?: {
                [key: string]: components["schemas"]["JsonValue"];
            };
            /**
             * @description Optional reasoning trace from a thinking-capable model
             * @default null
             */
            thinking?: components["schemas"]["ThinkingTrace"] | null;
        };
        /**
         * ThinkingStep
         * @description One step of a chain-of-thought trace.
         */
        ThinkingStep: {
            /**
             * Content
             * @description Reasoning step text
             */
            content: string;
            /**
             * Tokens Used
             * @description Optional token count
             * @default null
             */
            tokens_used?: number | null;
        };
        /**
         * ThinkingTrace
         * @description Captured reasoning trace from a thinking-capable model.
         */
        ThinkingTrace: {
            /**
             * Model Id
             * @description Producing model identifier
             * @default
             */
            model_id?: string;
            /**
             * Steps
             * @description Reasoning steps in order
             */
            steps?: components["schemas"]["ThinkingStep"][];
            /**
             * Total Tokens
             * @description Optional total tokens across steps
             * @default null
             */
            total_tokens?: number | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    "post_/api/detection/detect": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DetectionRequest"];
            };
        };
        responses: {
            /** @description Successful response. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DetectionResponse"];
                };
            };
        };
    };
    "post_/api/extract-claims": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ClaimExtractionRequest"];
            };
        };
        responses: {
            /** @description Successful response. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClaimExtractionResponse"];
                };
            };
        };
    };
    "post_/api/ontology/augment": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AugmentRequest"];
            };
        };
        responses: {
            /** @description Successful response. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AugmentResponse"];
                };
            };
        };
    };
    "post_/api/summarize": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SummarizeRequest"];
            };
        };
        responses: {
            /** @description Successful response. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SummarizeResponse"];
                };
            };
        };
    };
    "post_/api/synthesize-summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SummarySynthesisRequest"];
            };
        };
        responses: {
            /** @description Successful response. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SummarySynthesisResponse"];
                };
            };
        };
    };
}
