"""Type definitions for the model service.

This package provides centralized type definitions including Literal types,
TypedDicts, and Protocols for static type checking throughout the codebase.
"""

from src.types.literals import (
    ClaimExtractionStrategy,
    ClaimRelationType,
    ClaimSourceType,
    DeviceType,
    ExternalAPIProvider,
    FusionStrategy,
    InferenceFramework,
    OntologyCategory,
    Quantization,
    SpeedCategory,
    SynthesisStrategy,
    TaskType,
    ThumbnailSize,
)
from src.types.protocols import (
    AsyncModelLoader,
    AudioTranscriber,
    ExternalAPIClient,
    ModelLoader,
    ObjectDetector,
    SpeakerDiarizer,
    TextGenerator,
    VideoProcessor,
    VideoTracker,
    VisionLanguageModel,
    VoiceActivityDetector,
)
from src.types.typed_dicts import (
    APIUsageDict,
    BoundingBoxDict,
    ClaimDict,
    ClaimRelationDict,
    ClaimSourceDict,
    DetectionDict,
    DeviceConfigDict,
    ExternalAPIResponseDict,
    InferenceConfigDict,
    KeyFrameDict,
    LoadedModelInfoDict,
    MaskRLEDict,
    MemoryValidationDict,
    ModelConfigDict,
    ModelRequirementDict,
    OntologyTypeDict,
    TaskConfigDict,
    TrackingMaskDict,
    TranscriptSegmentDict,
)

__all__ = [
    # Literals
    "ClaimExtractionStrategy",
    "ClaimRelationType",
    "ClaimSourceType",
    "DeviceType",
    "ExternalAPIProvider",
    "FusionStrategy",
    "InferenceFramework",
    "OntologyCategory",
    "Quantization",
    "SpeedCategory",
    "SynthesisStrategy",
    "TaskType",
    "ThumbnailSize",
    # Protocols
    "AsyncModelLoader",
    "AudioTranscriber",
    "ExternalAPIClient",
    "ModelLoader",
    "ObjectDetector",
    "SpeakerDiarizer",
    "TextGenerator",
    "VideoProcessor",
    "VideoTracker",
    "VisionLanguageModel",
    "VoiceActivityDetector",
    # TypedDicts
    "APIUsageDict",
    "BoundingBoxDict",
    "ClaimDict",
    "ClaimRelationDict",
    "ClaimSourceDict",
    "DetectionDict",
    "DeviceConfigDict",
    "ExternalAPIResponseDict",
    "InferenceConfigDict",
    "KeyFrameDict",
    "LoadedModelInfoDict",
    "MaskRLEDict",
    "MemoryValidationDict",
    "ModelConfigDict",
    "ModelRequirementDict",
    "OntologyTypeDict",
    "TaskConfigDict",
    "TrackingMaskDict",
    "TranscriptSegmentDict",
]
