import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  docsSidebar: [
    'index',
    {
      type: 'category',
      label: 'Tutorial',
      link: {type: 'doc', id: 'tutorial/index'},
      items: [
        'tutorial/install',
        'tutorial/first-persona',
        'tutorial/annotate-a-video',
        'tutorial/summary-and-claims',
        'tutorial/export-import',
      ],
    },
    {
      type: 'category',
      label: 'Guides',
      link: {type: 'doc', id: 'guide/index'},
      items: [
        'guide/personas',
        'guide/ontologies',
        'guide/annotations',
        'guide/tracking',
        'guide/detection',
        'guide/world-state',
        'guide/summaries',
        'guide/claims',
        'guide/relations',
        'guide/wikidata',
        'guide/export-import',
        'guide/cross-user-imports',
        'guide/authentication',
        'guide/api-keys',
        'guide/audio-transcription',
        'guide/projects',
        'guide/groups',
        'guide/video-assignments',
        'guide/sharing',
        'guide/roles-permissions',
        'guide/admin-permissions',
        'guide/model-config',
        'guide/deployment',
        'guide/observability',
      ],
    },
    {
      type: 'category',
      label: 'Concepts',
      link: {type: 'doc', id: 'concepts/index'},
      items: [
        'concepts/architecture',
        'concepts/persona-ontologies',
        'concepts/annotation-model',
        'concepts/claims-model',
        'concepts/rbac',
        'concepts/data-isolation',
        'concepts/model-service',
      ],
    },
    {
      type: 'category',
      label: 'Reference',
      link: {type: 'doc', id: 'reference/index'},
      items: [
        'reference/api',
        'reference/data-model',
        'reference/rbac-permissions',
        'reference/environment-variables',
        'reference/docker',
        'reference/service-ports',
        'reference/keyboard-shortcuts',
        'reference/model-config',
        'reference/glossary',
      ],
    },
    {
      type: 'category',
      label: 'Project',
      link: {type: 'doc', id: 'project/index'},
      items: [
        'project/changelog',
        'project/contributing',
        'project/stability',
      ],
    },
  ],
};

export default sidebars;
